### ISSUE TITLE
dpos-pbft模拟过程出现“SyntaxError: Unexpected end of JSON input”

### ISSUE THREAD

**Issue by gx199112** [sqfasd/dpos-pbft#2]
Version
dpos-pbft 项目最新
https://github.com/sqfasd/dpos-pbft

Environment
win7 +nodeJs 8.9.0

Steps to reproduce
// 使用pbft
node main.js -p

What is expected?
得到模拟结果

What is actually happening?
运行一小段时间后报错
SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at Peer.onData_ (D:\Users\git\dpos-pbft\peer.js:64:20)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:246:13)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:594:20)

**Comment by cmxss** [comment]
可以留个联系方式吗？有问题向您请教

**Comment by RQWang1995** [comment]
请问这个问题怎么解决呢，谢谢
